#!/usr/bin/node

const fs = require('fs');
const cp = require('child_process');

const targetCulture = process.argv[2];
const fallbackCulture = process.argv[3] || 'en-ca';

if (!targetCulture) {
    console.error("specify target cutlure code");
    process.exit(-1);
}

const rootPath = process.argv[1].replace(/\/scripts\/[^\/]+$/, "");
const inputRootPath = `${rootPath}/src`;
const outputRootPath = `${rootPath}/GUI_USER`;
const resourceRootPath = `${rootPath}/resources`;

fs.readdirSync(inputRootPath)
    .filter(filename => filename.indexOf(".src.") > 0)
    .forEach(filename => {
        const outputFileName = filename.replace(".src.", ".");
        const inputFilePath = `${inputRootPath}/${filename}`;
        const outputFilePath = `${outputRootPath}/${outputFileName}`;
        const resourceFilePath = `${resourceRootPath}/${targetCulture}/${outputFileName}.json`;
        const fallbackResourceFilePath = `${resourceRootPath}/${fallbackCulture}/${outputFileName}.json`;
        if (fs.existsSync(resourceFilePath)) {
            cp.fork(`${__dirname}/applyrsc`, [ inputFilePath, outputFilePath, resourceFilePath, fallbackResourceFilePath ]);
        }
    });
