#!/usr/bin/node

const fs = require('fs');
const cp = require('child_process');

const rootPath = __dirname.replace(/\\/g, "/").replace(/\/[^\/]+$/, "");
const commonFilePath = `${rootPath}/GUI_USER.common`;
const buildRootPath = `${rootPath}/build`;

const baseCulture = "en-ca";
const cultures = [ "xx-zz", "en-us", "ja-jp" ];

for (const culture of cultures) {
    const cutlureResourceRootPath = `${rootPath}/resources/${culture}`;
    const cultureBuildRootPath = `${buildRootPath}/${culture}/GUI_USER`;
    // Ensure we delete the existing build
    if (fs.existsSync(cultureBuildRootPath)) {
        fs.rmdirSync(cultureBuildRootPath, { recursive: true });
    }
    cp.fork(`${__dirname}/fcopy`, [ commonFilePath, cultureBuildRootPath ]);
    cp.fork(`${__dirname}/applyrscs`, [ cultureBuildRootPath, culture, baseCulture ]);

    if (fs.existsSync(cutlureResourceRootPath)) {
        fs.readdirSync(cutlureResourceRootPath)
            .map(name => `${cutlureResourceRootPath}/${name}`)
            .filter(path => !path.endsWith(".json") && !fs.lstatSync(path).isDirectory())
            .map(path => {
                cp.fork(`${__dirname}/fcopy`, [ path, cultureBuildRootPath ]);
            })
    }
}
