#!/usr/bin/node

const fs = require('fs');
const cp = require('child_process');

const rootPath = __dirname.replace(/\\/g, "/").replace(/\/[^\/]+$/, "");
const xmlRootPath = `${rootPath}/GUI_USER.common`;
const outputRootPath = `${rootPath}/src`;
const baseCulture = "en-ca";
const resourceRootPath = `${rootPath}/resources`;
const resourceOutputPath = `${resourceRootPath}/${baseCulture}`;

if (!fs.existsSync(resourceOutputPath)) {
    fs.mkdirSync(resourceOutputPath);
}

if (!fs.existsSync(outputRootPath)) {
    fs.mkdirSync(outputRootPath);
}

fs.readdirSync(xmlRootPath)
    .filter(filename => filename.endsWith(".xml"))
    .forEach(filename => {
        const inputFilePath = `${xmlRootPath}/${filename}`;
        const outputFilePath = `${outputRootPath}/${filename.replace(/\.([^\.]+$)/, ".src.$1")}`;
        const resourceFilePath = `${resourceOutputPath}/${filename}.json`;
        cp.fork(`${__dirname}/gentpl`, [ inputFilePath, outputFilePath, resourceFilePath ]);
    });