#!/usr/bin/node

const fs = require('fs');
const cp = require('child_process');

const baseCulture = "en-ca";
const pseudoCulture = "xx-zz";
const rootPath = process.argv[1].replace(/\/scripts\/[^\/]+$/, "");
const resourceRootPath = `${rootPath}/resources`;
const inputResourcePath = `${resourceRootPath}/${baseCulture}`;
const outputResourcePath = `${resourceRootPath}/${pseudoCulture}`;

if (!fs.existsSync(outputResourcePath)) {
    fs.mkdirSync(outputResourcePath);
}

fs.readdirSync(inputResourcePath)
    .filter(filename => filename.endsWith("json"))
    .forEach(filename => {
        const inputFilePath = `${inputResourcePath}/${filename}`;
        const outputFilePath = `${outputResourcePath}/${filename}`;
        cp.fork(`${__dirname}/pseudoloc`, [ inputFilePath, outputFilePath ]);
    });